---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-abhi
  labels:
    app: nodejs-app-abhi
  namespace: nodejs-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app-abhi
  template:
    metadata:
      labels:
        app: nodejs-app-abhi
    spec:
      containers:
      - name: nodejs-app-abhi
        image: docker.io/abhimanyubajaj98/my-node-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        #env:
        #- name: APPDYNAMICS_AGENT_UNIQUE_HOST_ID
        #  value: $(cat /proc/self/cgroup | head -1 | awk -F '/' '{print $NF}' | cut -c 16-27)
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
  labels:
    app: nodejs-app-abhi
  namespace: nodejs-apps
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: nodejs-app-abhi
